# **Simplified Attention**

In [ ]:
import torch
import numpy as np

In [ ]:
inputs = torch.tensor(
[[ 0.32,-0.88 , 1.25 , 0.04 ,-0.52],
 [ 0.97, 0.10 ,-0.33 , 0.45 , 0.21],
 [-0.41, 1.17 , -0.73 , -0.62 , 0.87],
 [ 0.14, -0.55,  0.07 , 0.98 , 0.65],
 [-0.89, 0.34 , 0.41 , -0.21 , 0.03]]
)

In [ ]:
attention_scores = torch.mm(inputs, inputs.T)
attention_scores

tensor([[ 2.7113, -0.2813, -2.5505,  0.3175, -0.0955],
        [-0.2813,  1.3064, -0.1361,  0.6352, -1.0528],
        [-2.5505, -0.1361,  3.2112, -0.7941,  0.6197],
        [ 0.3175,  0.6352, -0.7941,  1.7099, -0.4692],
        [-0.0955, -1.0528,  0.6197, -0.4692,  1.1208]])

In [ ]:
attention_weights = torch.softmax(attention_scores, dim=-1) # These are also probabilities how much a query attends to other tokens
print(attention_weights)
print(attention_weights[0].sum())

tensor([[0.8285, 0.0416, 0.0043, 0.0756, 0.0500],
        [0.0999, 0.4887, 0.1155, 0.2498, 0.0462],
        [0.0028, 0.0311, 0.8838, 0.0161, 0.0662],
        [0.1392, 0.1913, 0.0458, 0.5603, 0.0634],
        [0.1335, 0.0512, 0.2729, 0.0919, 0.4505]])
tensor(1.0000)


In [ ]:
context_vector = torch.mm(attention_weights, inputs) # enriched embedding vector having information of semantics.
context_vector

tensor([[ 0.2697, -0.7445,  1.0446,  0.1128, -0.3677],
        [ 0.4525, -0.0256, -0.0843,  0.3874,  0.3149],
        [-0.3880,  1.0484, -0.6237, -0.5320,  0.7865],
        [ 0.2333, -0.3364,  0.1427,  0.5990,  0.3737],
        [-0.4075,  0.3096,  0.1418, -0.1454,  0.2520]])

In [ ]:
context_vector2 = attention_weights @ inputs # enriched embedding vector having information of semantics.
context_vector2

tensor([[ 0.2697, -0.7445,  1.0446,  0.1128, -0.3677],
        [ 0.4525, -0.0256, -0.0843,  0.3874,  0.3149],
        [-0.3880,  1.0484, -0.6237, -0.5320,  0.7865],
        [ 0.2333, -0.3364,  0.1427,  0.5990,  0.3737],
        [-0.4075,  0.3096,  0.1418, -0.1454,  0.2520]])

# **Self attention with trainable weights**

In [ ]:
clas